In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/uber.csv")

In [8]:
df.head()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [7]:
df.tail()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
199995,42598914,2012-10-28 10:49:00.00000053,3.0,2012-10-28 10:49:00 UTC,-73.987042,40.739367,-73.986525,40.740297,1
199996,16382965,2014-03-14 01:09:00.0000008,7.5,2014-03-14 01:09:00 UTC,-73.984722,40.736837,-74.006672,40.739620,1
199997,27804658,2009-06-29 00:42:00.00000078,30.9,2009-06-29 00:42:00 UTC,-73.986017,40.756487,-73.858957,40.692588,2
199998,20259894,2015-05-20 14:56:25.0000004,14.5,2015-05-20 14:56:25 UTC,-73.997124,40.725452,-73.983215,40.695415,1
199999,11951496,2010-05-15 04:08:00.00000076,14.1,2010-05-15 04:08:00 UTC,-73.984395,40.720077,-73.985508,40.768793,1

In [9]:
df.sample(20)

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
23157,32563699,2012-09-09 14:01:02.0000003,15.5,2012-09-09 14:01:02 UTC,-73.952950,40.776027,-73.990172,40.751220,1
58786,22695617,2012-06-17 20:54:22.0000003,4.5,2012-06-17 20:54:22 UTC,-74.012606,40.715469,-74.004580,40.717152,1
178673,14362597,2014-07-24 13:17:00.00000095,5.5,2014-07-24 13:17:00 UTC,-74.015450,40.717945,-74.007425,40.719885,1
47605,35286512,2013-05-07 21:01:00.00000085,16.5,2013-05-07 21:01:00 UTC,-73.981982,40.755732,-74.010742,40.725117,5
3338,52885638,2009-10-19 10:40:00.000000149,7.3,2009-10-19 10:40:00 UTC,-74.013337,40.704837,-74.014528,40.715528,1
134670,37979712,2013-11-27 16:05:29.0000002,9.5,2013-11-27 16:05:29 UTC,-73.988620,40.748807,-73.976793,40.739165,2
157663,42363697,2012-06-09 23:30:51.0000007,4.9,2012-06-09 23:30:51 UTC,-73.944378,40.794807,-73.939007,40.804733,1
27937,43141241,2011-06-09 11:09:04.0000004,13.3,2011-06-09 11:09:04 UTC,-73.976600,40.752600,-74.006300,40.723000,1
199769,8758727,2011-08-19 19:48:08.0000001,5.3,2011-08-19 19:48:08 UTC,-73.978046,40.778402,-73.972720,40.784139,1
81613,53460760,2015-05-13 21:00:13.00000014,7.0,2015-05-13 21:00:13 UTC,-73.970993,40.758595,-73.978790,40.741074,1
72183,9302503,2010-11-14 02:03:41.0000005,20.1,2010-11-14 02:03:41 UTC,-73.949023,40.744459,-73.993846,40.664621,1
90981,43701603,2013-03-12 14:54:56.0000001,4.5,2013-03-12 14:54:56 UTC,-73.942777,40.796995,-73.939447,40.790350,1
46453,21261823,2014-10-16 09:09:34.0000003,8.5,2014-10-16 09:09:34 UTC,-73.993428,40.727969,-74.008546,40.719007,1
78276,38204588,2014-09-27 17:52:37.0000002,11.5,2014-09-27 17:52:37 UTC,-73.978893,40.753561,-73.955698,40.776383,1
87011,34299992,2010-01-29 17:28:25.0000002,15.3,2010-01-29 17:28:25 UTC,-73.997922,40.682918,-73.987816,40.738132,1
45377,17275221,2012-07-24 08:50:11.0000002,7.3,2012-07-24 08:50:11 UTC,-73.994790,40.740377,-74.006002,40.720298,1
60969,8844833,2012-02-29 20:46:23.0000001,8.5,2012-02-29 20:46:23 UTC,-73.970113,40.797035,-73.984927,40.768436,1
79709,43417897,2012-01-23 17:29:22.0000001,4.9,2012-01-23 17:29:22 UTC,-74.006234,40.716847,-74.001182,40.728979,1
157455,52198894,2010-07-06 08:12:34.0000003,8.1,2010-07-06 08:12:34 UTC,-73.980349,40.770311,-73.977509,40.753881,1
102470,37228656,2012-05-10 18:35:00.00000021,8.9,2012-05-10 18:35:00 UTC,-73.974990,40.792747,-73.965760,40.773642,1

In [10]:
df.shape

(200000, 9)

In [11]:
df.columns

Index(['Unnamed: 0', 'key', 'fare_amount', 'pickup_datetime',
       'pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude', 'passenger_count'],
      dtype='str')

In [12]:
df.dtypes

Unnamed: 0             int64
key                      str
fare_amount          float64
pickup_datetime          str
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64
dtype: object

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         200000 non-null  int64
 1   key                200000 non-null  str
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  str
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 23.4 MB

In [14]:
df.describe()

,Unnamed: 0,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,2.000000e+05,200000.000000,200000.000000,200000.000000,199999.000000,199999.000000,200000.000000
mean,2.771250e+07,11.359955,-72.527638,39.935885,-72.525292,39.923890,1.684535
std,1.601382e+07,9.901776,11.437787,7.720539,13.117408,6.794829,1.385997
min,1.000000e+00,-52.000000,-1340.648410,-74.015515,-3356.666300,-881.985513,0.000000
25%,1.382535e+07,6.000000,-73.992065,40.734796,-73.991407,40.733823,1.000000
50%,2.774550e+07,8.500000,-73.981823,40.752592,-73.980093,40.753042,1.000000
75%,4.155530e+07,12.500000,-73.967154,40.767158,-73.963658,40.768001,2.000000
max,5.542357e+07,499.000000,57.418457,1644.421482,1153.572603,872.697628,208.000000

In [15]:
df.isnull().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["fare_amount"].describe()

count    200000.000000
mean         11.359955
std           9.901776
min         -52.000000
25%           6.000000
50%           8.500000
75%          12.500000
max         499.000000
Name: fare_amount, dtype: float64

In [18]:
df["passenger_count"].value_counts().sort_index()

passenger_count
0         709
1      138425
2       29428
3        8881
4        4276
5       14009
6        4271
208         1
Name: count, dtype: int64

In [19]:
(df["fare_amount"] < 0).sum()

np.int64(17)

In [29]:
(df["fare_amount"] == 0).sum()

np.int64(5)

In [22]:
df[df["passenger_count"] <= 0]

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
333,2137942,2011-08-05 07:03:08.0000001,10.1,2011-08-05 07:03:08 UTC,-74.013900,40.707800,-73.992300,40.749300,0
908,8484351,2011-09-06 12:25:19.0000002,11.7,2011-09-06 12:25:19 UTC,-73.981000,40.764600,-73.962900,40.778400,0
926,32941306,2012-03-26 18:11:24.0000002,3.3,2012-03-26 18:11:24 UTC,-73.979978,40.765821,-73.983894,40.766873,0
2000,12591041,2012-04-20 15:07:57.0000003,15.7,2012-04-20 15:07:57 UTC,-73.975285,40.750138,-73.974729,40.783151,0
3011,39400625,2012-01-07 19:19:08.0000004,6.1,2012-01-07 19:19:08 UTC,-73.977900,40.789100,-73.983700,40.773600,0
...,...,...,...,...,...,...,...,...,...
196797,26965490,2011-01-17 15:52:26.0000002,3.3,2011-01-17 15:52:26 UTC,-74.000760,40.757637,-74.004852,40.751947,0
197103,49116579,2011-12-10 15:33:12.0000008,7.3,2011-12-10 15:33:12 UTC,0.000000,0.000000,0.000000,0.000000,0
198872,12988511,2011-09-20 19:55:05.0000001,5.7,2011-09-20 19:55:05 UTC,-73.980300,40.742800,-73.967900,40.755600,0
198902,54393172,2011-08-22 21:10:56.0000002,12.1,2011-08-22 21:10:56 UTC,-73.996700,40.737200,-74.008500,40.704000,0
198953,47743848,2012-04-13 08:30:39.0000001,3.7,2012-04-13 08:30:39 UTC,-73.844310,40.721270,-73.842987,40.713435,0

In [28]:
invalid_long = (
    (df["pickup_longitude"] < -180) | (df["pickup_longitude"] > 180)
).sum()

invalid_lat = (
    (df["pickup_latitude"] < -90) | (df["pickup_latitude"] >90)
).sum()
print(invalid_long)
print(invalid_lat)

7
4