In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("../data/raw/uber.csv")

In [17]:
df_clean = df.copy()

In [18]:
print(f"Initial rows: {len(df_clean)}")
print(f"Initial columns: {df_clean.shape[1]}")

Initial rows: 200000
Initial columns: 9

In [5]:
df_clean[df_clean.isnull().any(axis=1)]

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
87946,32736015,2013-07-02 03:51:57.0000001,24.1,2013-07-02 03:51:57 UTC,-73.950581,40.779692,NaN,NaN,0

In [19]:
before = len(df_clean)
df_clean = df_clean.dropna()
after = len(df_clean)
print(f"Rows removed: {before-after}")
print(f"Remaining rows: {after}")

Rows removed: 1
Remaining rows: 199999

In [8]:
df_clean[df_clean["fare_amount"] <= 0]

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
20744,25344154,2015-04-22 23:25:07.0000008,0.00,2015-04-22 23:25:07 UTC,-73.658897,40.805199,-73.658897,40.805199,1
22182,22994576,2010-03-20 02:59:51.0000002,0.00,2010-03-20 02:59:51 UTC,-73.994366,40.755395,-73.998718,40.854853,2
63395,30260042,2015-03-03 23:07:41.0000008,-5.00,2015-03-03 23:07:41 UTC,-73.992249,40.748936,-73.988518,40.748180,1
71246,51325304,2010-02-11 21:47:10.0000001,-3.30,2010-02-11 21:47:10 UTC,-73.952725,40.768235,-73.949928,40.772208,2
79903,50284253,2015-05-01 14:43:02.0000004,-3.50,2015-05-01 14:43:02 UTC,-73.982430,40.775024,-73.981750,40.778439,1
87467,10649069,2015-01-04 03:51:13.0000002,0.00,2015-01-04 03:51:13 UTC,-73.969475,40.807503,0.000000,0.000000,2
89322,26673143,2010-03-09 08:26:10.0000006,-49.57,2010-03-09 08:26:10 UTC,-73.972772,40.785657,-73.972867,40.785500,5
92063,10267585,2010-03-12 08:49:10.0000002,-23.70,2010-03-12 08:49:10 UTC,-73.952740,40.768233,-74.007028,40.707338,3
98875,51135168,2015-03-20 21:31:14.0000007,-52.00,2015-03-20 21:31:14 UTC,-74.000359,40.728729,-74.005699,40.728680,5
104080,21688700,2010-03-09 20:25:10.0000002,-7.30,2010-03-09 20:25:10 UTC,-73.952623,40.766942,-73.953787,40.784882,1
111589,13971251,2015-02-23 19:26:44.0000004,-52.00,2015-02-23 19:26:44 UTC,-73.984665,40.759026,0.000000,0.000000,5
139272,40714150,2010-02-23 18:52:10.0000003,-6.90,2010-02-23 18:52:10 UTC,-73.988727,40.736445,-73.977622,40.750487,1
148803,34933571,2010-02-12 10:50:10.0000005,-5.70,2010-02-12 10:50:10 UTC,-73.977300,40.742783,-73.988837,40.747465,3
150301,52122967,2015-06-18 07:41:12.0000001,-3.00,2015-06-18 07:41:12 UTC,-74.004646,40.707355,-74.004013,40.707699,1
151681,34292338,2010-02-17 05:46:10.0000001,-10.90,2010-02-17 05:46:10 UTC,-73.964257,40.760630,-73.994222,40.761533,1
156738,36776406,2015-02-17 08:48:08.0000005,0.00,2015-02-17 08:48:08 UTC,-73.937714,40.758541,-73.937721,40.758541,1
157412,8135931,2015-05-06 03:47:38.0000001,-3.50,2015-05-06 03:47:38 UTC,-73.986084,40.762146,-73.980476,40.759823,1
164056,29575269,2010-03-16 15:27:10.0000003,-50.50,2010-03-16 15:27:10 UTC,-73.784868,40.648677,-73.976975,40.763522,3
179111,8191651,2015-02-12 22:53:28.0000004,-3.50,2015-02-12 22:53:28 UTC,-73.989059,40.760181,-73.986649,40.761829,1
180444,29504446,2015-05-10 04:26:03.0000005,-3.00,2015-05-10 04:26:03 UTC,-73.983727,40.725910,-73.986099,40.722450,2
190925,19185220,2015-05-01 23:25:34.0000002,-5.50,2015-05-01 23:25:34 UTC,-73.988701,40.742649,-73.985924,40.735001,1
197172,44172118,2015-02-13 07:35:32.0000002,0.00,2015-02-13 07:35:32 UTC,0.000000,0.000000,0.000000,0.000000,5

In [20]:
before = len(df_clean)
df_clean = df_clean[df_clean["fare_amount"] > 0]
after = len(df_clean)
print(f"Rows removed: {before-after}")
print(f"Remaining rows: {after}")

Rows removed: 22
Remaining rows: 199977

In [21]:
before = len(df_clean)
df_clean = df_clean[(df_clean["passenger_count"] > 0) & (df_clean["passenger_count"] < 7)]
after = len(df_clean)
print(f"Rows removed: {before-after}")
print(f"Remaining rows: {after}")

Rows removed: 709
Remaining rows: 199268

In [22]:
invalid_coords = df_clean[
    (df_clean["pickup_longitude"] < -180) |
    (df_clean["pickup_longitude"] > 180) |
    (df_clean["pickup_latitude"] < -90) |
    (df_clean["pickup_latitude"] > 90) |
    (df_clean["dropoff_longitude"] < -180) |
    (df_clean["dropoff_longitude"] > 180) |
    (df_clean["dropoff_latitude"] < -90) |
    (df_clean["dropoff_latitude"] > 90)
]

invalid_coords

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
4949,42931506,2012-04-28 00:58:00.000000235,4.9,2012-04-28 00:58:00 UTC,-748.016667,40.739957,-74.003570,40.734192,1
32549,5634081,2012-06-16 10:04:00.00000061,15.7,2012-06-16 10:04:00 UTC,-74.016055,40.715155,-737.916665,40.697862,2
48506,1055960,2011-11-05 23:26:00.000000309,33.7,2011-11-05 23:26:00 UTC,-735.200000,40.770092,-73.980187,40.765530,1
56617,14257861,2012-03-11 07:24:00.00000031,8.1,2012-03-11 07:24:00 UTC,-73.960828,404.433332,-73.988357,40.769037,1
61793,2849369,2012-06-13 05:45:00.0000006,8.5,2012-06-13 05:45:00 UTC,-73.951385,401.066667,-73.982110,40.754117,1
75851,33249845,2011-11-05 00:22:00.00000051,15.7,2011-11-05 00:22:00 UTC,-1340.648410,1644.421482,-3356.666300,872.697628,1
91422,23566642,2011-05-18 13:24:00.000000213,16.1,2011-05-18 13:24:00 UTC,57.418457,1292.016128,1153.572603,-881.985513,1
103745,16826862,2011-10-14 19:04:00.000000202,12.9,2011-10-14 19:04:00 UTC,-736.216667,40.767035,-73.982377,40.725562,1
139447,39981694,2012-01-20 11:50:00.00000088,13.7,2012-01-20 11:50:00 UTC,-74.011042,40.709780,-73.983163,493.533332,4
144253,9421322,2009-08-26 11:55:00.00000023,7.3,2009-08-26 11:55:00 UTC,-768.550000,40.757812,-73.997040,40.740007,1
161652,25264921,2010-05-12 12:19:00.00000098,4.1,2010-05-12 12:19:00 UTC,-735.433332,40.740605,-74.006373,40.739607,1
199936,44787414,2012-07-21 16:19:00.00000099,4.1,2012-07-21 16:19:00 UTC,-736.400000,40.774307,-73.982215,40.769672,5

In [23]:
before = len(df_clean)

df_clean = df_clean[
    (df_clean["pickup_longitude"].between(-180, 180)) &
    (df_clean["pickup_latitude"].between(-90, 90)) &
    (df_clean["dropoff_longitude"].between(-180, 180)) &
    (df_clean["dropoff_latitude"].between(-90, 90))
]

after = len(df_clean)

print(f"Rows removed: {before-after}")
print(f"Remaining rows: {after}")

Rows removed: 12
Remaining rows: 199256

In [24]:
zero_coords = df_clean[
    (
        (df_clean["pickup_longitude"] == 0) &
        (df_clean["pickup_latitude"] == 0)
    ) |
    (
        (df_clean["dropoff_longitude"] == 0) &
        (df_clean["dropoff_latitude"] == 0)
    )
]

zero_coords

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
7,44195482,2012-12-11 13:52:00.00000029,2.5,2012-12-11 13:52:00 UTC,0.0,0.0,0.0,0.0,1
11,6379048,2011-05-23 22:15:00.00000086,8.5,2011-05-23 22:15:00 UTC,0.0,0.0,0.0,0.0,1
65,21993993,2014-05-05 19:27:00.00000034,6.0,2014-05-05 19:27:00 UTC,0.0,0.0,0.0,0.0,1
92,1454546,2011-12-02 14:07:00.000000207,6.1,2011-12-02 14:07:00 UTC,0.0,0.0,0.0,0.0,1
120,17358122,2010-08-20 19:39:48.0000003,6.5,2010-08-20 19:39:48 UTC,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...
199718,49162936,2011-08-19 07:16:00.00000037,4.9,2011-08-19 07:16:00 UTC,0.0,0.0,0.0,0.0,1
199724,46007628,2013-10-11 11:25:41.0000004,7.5,2013-10-11 11:25:41 UTC,0.0,0.0,0.0,0.0,1
199880,35013970,2014-02-22 06:45:46.0000002,6.5,2014-02-22 06:45:46 UTC,0.0,0.0,0.0,0.0,1
199883,44115598,2012-09-10 17:39:00.00000090,12.5,2012-09-10 17:39:00 UTC,0.0,0.0,0.0,0.0,2
199963,50075618,2012-09-22 07:46:01.0000002,39.0,2012-09-22 07:46:01 UTC,0.0,0.0,0.0,0.0,1

In [25]:
before = len(df_clean)

df_clean = df_clean[
    ~(
        (
            (df_clean["pickup_longitude"] == 0) &
            (df_clean["pickup_latitude"] == 0)
        ) |
        (
            (df_clean["dropoff_longitude"] == 0) &
            (df_clean["dropoff_latitude"] == 0)
        )
    )
]

after = len(df_clean)

print(f"Rows removed: {before-after}")
print(f"Remaining rows: {after}")

Rows removed: 3923
Remaining rows: 195333

In [26]:
df_clean["pickup_datetime"] = pd.to_datetime(df_clean["pickup_datetime"])

In [27]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 195333 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         195333 non-null  int64
 1   key                195333 non-null  str
 2   fare_amount        195333 non-null  float64
 3   pickup_datetime    195333 non-null  datetime64[us, UTC]
 4   pickup_longitude   195333 non-null  float64
 5   pickup_latitude    195333 non-null  float64
 6   dropoff_longitude  195333 non-null  float64
 7   dropoff_latitude   195333 non-null  float64
 8   passenger_count    195333 non-null  int64
dtypes: datetime64[us, UTC](1), float64(5), int64(2), str(1)
memory usage: 20.1 MB

In [28]:
df_clean.drop(columns=["Unnamed: 0"], inplace=True)

In [29]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 195333 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                195333 non-null  str
 1   fare_amount        195333 non-null  float64
 2   pickup_datetime    195333 non-null  datetime64[us, UTC]
 3   pickup_longitude   195333 non-null  float64
 4   pickup_latitude    195333 non-null  float64
 5   dropoff_longitude  195333 non-null  float64
 6   dropoff_latitude   195333 non-null  float64
 7   passenger_count    195333 non-null  int64
dtypes: datetime64[us, UTC](1), float64(5), int64(1), str(1)
memory usage: 18.6 MB

In [30]:
df_clean.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,195333.000000,195333.000000,195333.000000,195333.000000,195333.000000,195333.000000
mean,11.352350,-73.900111,40.686478,-73.899195,40.685881,1.690093
std,9.804447,2.825267,2.656316,2.820956,2.661708,1.306093
min,0.010000,-93.824668,-74.015515,-75.458979,-74.015750,1.000000
25%,6.000000,-73.992267,40.736390,-73.991592,40.735265,1.000000
50%,8.500000,-73.982101,40.753275,-73.980521,40.753723,1.000000
75%,12.500000,-73.968313,40.767537,-73.965314,40.768320,2.000000
max,499.000000,40.808425,48.018760,40.831932,45.031598,6.000000

In [31]:
df_clean.shape

(195333, 8)

In [32]:
df_clean.isnull().sum()

key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [33]:
df_clean.duplicated().sum()

np.int64(0)

In [34]:
df_clean.to_csv("../data/processed/uber_clean.csv", index=False)

In [35]:
clean_df = pd.read_csv("../data/processed/uber_clean.csv")
clean_df.head()

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06+00:00,-73.999817,40.738354,-73.999512,40.723217,1
1,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56+00:00,-73.994355,40.728225,-73.994710,40.750325,1
2,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00+00:00,-74.005043,40.740770,-73.962565,40.772647,1
3,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21+00:00,-73.976124,40.790844,-73.965316,40.803349,3
4,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00+00:00,-73.925023,40.744085,-73.973082,40.761247,5